In [83]:
!pip install numpy pandas scikit-learn matplotlib

Requirement already satisfied: numpy in .\venv\Lib\site-packages (2.4.4)
Requirement already satisfied: pandas in .\venv\Lib\site-packages (3.0.2)
Requirement already satisfied: scikit-learn in .\venv\Lib\site-packages (1.8.0)
Requirement already satisfied: matplotlib in .\venv\Lib\site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in .\venv\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in .\venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in .\venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\venv\Lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\venv\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in .\venv\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [85]:
df=pd.read_csv('Housing.csv')

In [86]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [87]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [88]:
df[['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']]=pd.get_dummies(df[['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']],drop_first=True)

In [89]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,True,False,False,False,True,2,True,furnished
1,12250000,8960,4,4,4,True,False,False,False,True,3,False,furnished
2,12250000,9960,3,2,2,True,False,True,False,False,2,True,semi-furnished
3,12215000,7500,4,2,2,True,False,True,False,True,3,True,furnished
4,11410000,7420,4,1,2,True,True,True,False,True,2,False,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,True,False,True,False,False,2,False,unfurnished
541,1767150,2400,3,1,1,False,False,False,False,False,0,False,semi-furnished
542,1750000,3620,2,1,1,True,False,False,False,False,0,False,unfurnished
543,1750000,2910,3,1,1,False,False,False,False,False,0,False,furnished
544,1750000,3850,3,1,2,True,False,False,False,False,0,False,unfurnished

In [90]:
df[['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']] = \
df[['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']].astype(int)

In [91]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished

In [92]:
df['prefarea']=(df['prefarea']).astype(int)

In [93]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished

In [94]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    int64
 6   guestroom         545 non-null    int64
 7   basement          545 non-null    int64
 8   hotwaterheating   545 non-null    int64
 9   airconditioning   545 non-null    int64
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    int64
 12  furnishingstatus  545 non-null    str
dtypes: int64(12), str(1)
memory usage: 55.5 KB

In [96]:
from sklearn.preprocessing import OneHotEncoder
encode = OneHotEncoder(sparse_output=False)
encoded = encode.fit_transform(df[['furnishingstatus']])
edf=pd.DataFrame(encoded,columns=encode.get_feature_names_out())
df=df.drop(['furnishingstatus'],axis=1)
df=pd.concat([df,edf],axis=1)

In [97]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1.0,0.0,0.0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1.0,0.0,0.0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0.0,1.0,0.0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1.0,0.0,0.0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,0.0,0.0,1.0
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,0.0,1.0,0.0
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,0.0,0.0,1.0
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,1.0,0.0,0.0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,0.0,0.0,1.0

In [98]:
df.to_csv('processed-housepricing.csv')

In [99]:
ndf=pd.read_csv('processed-housepricing.csv')

In [100]:
ndf

,Unnamed: 0,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1.0,0.0,0.0
1,1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1.0,0.0,0.0
2,2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0.0,1.0,0.0
3,3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1.0,0.0,0.0
4,4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,540,1820000,3000,2,1,1,1,0,1,0,0,2,0,0.0,0.0,1.0
541,541,1767150,2400,3,1,1,0,0,0,0,0,0,0,0.0,1.0,0.0
542,542,1750000,3620,2,1,1,1,0,0,0,0,0,0,0.0,0.0,1.0
543,543,1750000,2910,3,1,1,0,0,0,0,0,0,0,1.0,0.0,0.0
544,544,1750000,3850,3,1,2,1,0,0,0,0,0,0,0.0,0.0,1.0

In [101]:
ndf

,Unnamed: 0,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1.0,0.0,0.0
1,1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1.0,0.0,0.0
2,2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0.0,1.0,0.0
3,3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1.0,0.0,0.0
4,4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,540,1820000,3000,2,1,1,1,0,1,0,0,2,0,0.0,0.0,1.0
541,541,1767150,2400,3,1,1,0,0,0,0,0,0,0,0.0,1.0,0.0
542,542,1750000,3620,2,1,1,1,0,0,0,0,0,0,0.0,0.0,1.0
543,543,1750000,2910,3,1,1,0,0,0,0,0,0,0,1.0,0.0,0.0
544,544,1750000,3850,3,1,2,1,0,0,0,0,0,0,0.0,0.0,1.0

In [103]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.ensemble import GradientBoostingRegressor,RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

In [110]:
#drop the 'unnamed: 0' column which is causing the data leak 
x = ndf.drop(columns=['price','Unnamed: 0'])
y = ndf['price']
#Re-split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
#Rescale the area feature
x_train[['area']]=scaler.fit_transform(x_train[['area']])
x_test[['area']]=scaler.transform(x_test[['area']])
print("Data leak fixed by removing 'Unnamed: 0'.Running models...")
models={
    'Linear Regression' : LinearRegression(),
    'Ridge':Ridge(random_state=42),
    'Lasso':Lasso(random_state=42),

    'Random Forest Regressor':RandomForestRegressor(random_state=42),
    'Gradient Boosting Regressor':GradientBoostingRegressor(random_state=42),

    'KNN':KNeighborsRegressor()
}
#Re-run evaluations
for name, model in models.items():
    try:
        model.fit(x_train,y_train)
        y_pred=model.predict(x_test)
        print(f'Model Name:{name}')
        print(f'R2 Score:{r2_score(y_test,y_pred):.3f}')
        print(f'MAE:{mean_absolute_error(y_test,y_pred):.3f}\n')
    except Exception as e:
        print(f'Model Name: {name}Failed: {e}')

Data leak fixed by removing 'Unnamed: 0'.Running models...
Model Name:Linear Regression
R2 Score:0.653
MAE:970043.404

Model Name:Ridge
R2 Score:0.652
MAE:970543.940

Model Name:Lasso
R2 Score:0.653
MAE:970044.760

Model Name:Random Forest Regressor
R2 Score:0.612
MAE:1019736.261

Model Name:Gradient Boosting Regressor
R2 Score:0.666
MAE:966840.670

Model Name:KNN
R2 Score:0.514
MAE:1066911.229

In [111]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1.0,0.0,0.0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1.0,0.0,0.0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0.0,1.0,0.0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1.0,0.0,0.0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,0.0,0.0,1.0
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,0.0,1.0,0.0
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,0.0,0.0,1.0
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,1.0,0.0,0.0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,0.0,0.0,1.0